/**
 * SkweedudoMOBILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");
const baseController = require("../../lib/Controllers/BaseController");

const controller = testerlib.MiscController;
const AuthRequest = testerlib.AuthRequest;
const CreateSkweedudorRequest = testerlib.CreateSkweedudorRequest;

describe("MiscController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * TODO: Add Description
     */
    it("should testAuth response", function testAuthTest(done) {
        // parameters for the API call
        let contentType = 'application/json';
        let body = baseController.getObjectMapper().mapObject({
  "strategy": "local",
  "email": "twahome@onfonmedia.com",
  "password": "1234"
}, 'AuthRequest');

        controller.createAuth(contentType, body, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        }).catch(() => undefined);
    });

    /**
     * TODO: Add Description
     */
    it("should testCreateSkweedudor response", function testCreateSkweedudorTest(done) {
        // parameters for the API call
        let contentType = 'application/json';
        let body = baseController.getObjectMapper().mapObject({
  "strategy": "local",
  "name": "Timothy Wahome",
  "email": "twahome@onfonmedia.com",
  "password": "1234"
}, 'CreateSkweedudorRequest');

        controller.createSkweedudor(contentType, body, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        }).catch(() => undefined);
    });

    /**
     * TODO: Add Description
     */
    it("should testGetSkweedudor response", function testGetSkweedudorTest(done) {
        controller.getSkweedudor(function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        }).catch(() => undefined);
    });
});
