/**
 * SkweedudoMOBILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const AuthRequest = require('../lib/Models/AuthRequest');
const CreateSkweedudorRequest = require('../lib/Models/CreateSkweedudorRequest');

const classMap = {
    AuthRequest,
    CreateSkweedudorRequest,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
